services:
  # -------------------------------------------
  # Creator Service (URL Creation Service)
  # -------------------------------------------
  creator-service:
    build:
      context: .
      dockerfile: services/creator-service/Dockerfile
      args:
        APP_NAME: creator # Tells Dockerfile which application to build
    command: /usr/local/bin/creator # Run this binary when container starts
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CREATOR_PORT=${CREATOR_PORT:-8081} # Get from .env file, use 8081 if not set
      - BASE_URL=http://localhost:8080
    labels:
      # --- Traefik Settings (for API Gateway) ---
      - "traefik.enable=true"
      - "traefik.http.routers.creator.rule=PathPrefix(`/api`)" # Route requests starting with /api here
      - "traefik.http.services.creator.loadbalancer.server.port=8081"
      # --- CORS Middleware Definition for Traefik ---
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=http://localhost:5173,http://localhost:3000"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=Origin,Content-Type,Accept,Authorization"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowCredentials=true"
      # --- Apply CORS Middleware to the Router ---
      - "traefik.http.routers.creator.middlewares=cors-headers"

  # -------------------------------------------
  # Redirector Service (Redirection Service)
  # -------------------------------------------
  redirector-service:
    build:
      context: .
      dockerfile: services/redirector-service/Dockerfile
      args:
        APP_NAME: redirector
    command: /usr/local/bin/redirector
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIRECTOR_PORT=${REDIRECTOR_PORT:-8082}
    labels:
      # --- Traefik Settings (for API Gateway) ---
      - "traefik.enable=true"
      - "traefik.http.routers.redirector.rule=PathPrefix(`/`)" # Route all other incoming requests here
      - "traefik.http.routers.redirector.priority=1" # Low priority to not override other rules
      - "traefik.http.services.redirector.loadbalancer.server.port=8082"

  # -------------------------------------------
  # Analytics Service (Analytics Service)
  # -------------------------------------------
  # analytics-service:
  #   build:
  #     context: .
  #     dockerfile: services/analytics-service/Dockerfile
  #     args:
  #       APP_NAME: analytics
  #   command: /usr/local/bin/analytics
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - ANALYTICS_PORT=${ANALYTICS_PORT:-8083}
  #   labels:
  #     # --- Traefik Settings (for API Gateway) ---
  #     - "traefik.enable=true"
  #     # Add rules here if this service needs to be exposed externally
  #     # For now, it will only run internally
  #     - "traefik.http.services.analytics.loadbalancer.server.port=8083"

  # -------------------------------------------
  # Traefik (API Gateway / Receptionist)
  # -------------------------------------------
  traefik:
    image: "traefik:v3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Only expose services with labels
      - "--entrypoints.web.address=:80"
      - "--accesslog=true" # Enable access logs
    ports:
      - "8080:80"      # For incoming requests from the outside world (HOST:CONTAINER)
      - "8081:8080"    # For Traefik Dashboard (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"