apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        # github actions'ın push'ladığı imajı kullan. sha'yı en son commit'ten al.
        image: veritasacr.azurecr.io/veritas/analytics-service:597dda5928a29f3f44ec8f5cd5ad28ad4e8b12bb
        envFrom:
          - secretRef:
              name: veritas-secrets
          - configMapRef:
              name: veritas-config
# analytics-service doesn't expose any HTTP endpoints, it only consumes NATS events
# so no Service resource is needed 