apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirector-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirector-service
  template:
    metadata:
      labels:
        app: redirector-service
    spec:
      containers:
      - name: redirector-service
        # github actions'ın push'ladığı imajı kullan. sha'yı en son commit'ten al.
        image: veritasacr.azurecr.io/veritas/redirector-service:e622f8de896ae655e7d32a507c8bd953195f0daa 
        ports:
        - containerPort: 8082
        envFrom:
          - secretRef:
              name: veritas-secrets
          - configMapRef:
              name: veritas-config
---
apiVersion: v1
kind: Service
metadata:
  name: redirector-service
spec:
  selector:
    app: redirector-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8082 