apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veritas-ingress
spec:
  rules:
  # kural 1: ana domain için (frontend ve api)
  - host: "134.112.10.179.nip.io" # örn: veritas.com veya <EXTERNAL-IP>.nip.io
    http:
      paths:
      # /api istekleri creator-service'e gitsin
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: creator-service
            port:
              number: 80
      # diğer tüm istekler frontend'e gitsin
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  # kural 2: subdomain için (sadece redirector)
  - host: "go.134.112.10.179.nip.io" # örn: go.veritas.com veya go.<EXTERNAL-IP>.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redirector-service
            port:
              number: 80