apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veritas-ingress
spec:
  rules:
  # rule 1: for main domain (frontend and api)
  - host: "VERITAS_IP.nip.io" # e.g.: veritas.com or <EXTERNAL-IP>.nip.io
    http:
      paths:
      # /api requests should go to creator-service
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: creator-service
            port:
              number: 80
      # all other requests should go to frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  # rule 2: for subdomain (only redirector)
  - host: "go.VERITAS_IP.nip.io" # e.g.: go.veritas.com or go.<EXTERNAL-IP>.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redirector-service
            port:
              number: 80