// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, originalUrl string) (int64, error)
	DeleteURL(ctx context.Context, id int64) error
	GetURLByShortCode(ctx context.Context, shortCode string) (string, error)
	UpdateShortCode(ctx context.Context, arg UpdateShortCodeParams) error
}

var _ Querier = (*Queries)(nil)
