// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: urls.sql

package database

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original_url) VALUES ($1) RETURNING id
`

func (q *Queries) CreateURL(ctx context.Context, originalUrl string) (int64, error) {
	row := q.db.QueryRow(ctx, createURL, originalUrl)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT original_url FROM urls WHERE short_code = $1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (string, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}

const updateShortCode = `-- name: UpdateShortCode :exec
UPDATE urls SET short_code = $1 WHERE id = $2
`

type UpdateShortCodeParams struct {
	ShortCode string `json:"short_code"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateShortCode(ctx context.Context, arg UpdateShortCodeParams) error {
	_, err := q.db.Exec(ctx, updateShortCode, arg.ShortCode, arg.ID)
	return err
}
